env: dev

app_project: gosoline
app_family: example
app_name: stream-kinesis-consumer

stream:
  consumer:
    default:
      input: consumer

  input:
    consumer:
      type: kinesis
      application: stream-kinesis-output
      stream_name: exampleRecord
