app:
  env: dev
  name: stream-kinesis-consumer
  tags:
    project: gosoline
    family: example
    group: grp

stream:
  consumer:
    default:
      input: consumer

  input:
    consumer:
      type: kinesis
      application: stream-kinesis-output
      stream_name: exampleRecord
