env: dev

app_project: gosoline
app_family: example
app_group: money-exchange
app_name: money-exchange

api:
  port: 8080

kvstore:
  currency:
    type: chain
    in_memory:
      max_size: 500000
    application: money-exchange
    elements: [inMemory]
    ttl: 30m