redentials
app:
  env: dev
  name: credentials
  tags:
    project: justtrack
    family: gosoline
    group: examples

cloud:
  aws:
    defaults:
      credentials:
        access_key_id: justtrack
        secret_access_key: justtrack
