name: "Update markdown files"

on: [push]

jobs:
  update_markdown_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: checkout on the lastest commit
        uses: actions/checkout@v2
        with:
          repository: ''
          ref: ''

      - name: setup golang
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.17.0'

      - name: "running embedmd"
        run: |
          go install github.com/campoy/embedmd@latest
          embedmd -w $(find . | grep *.md)

      - name: "running structmd"
        run: |
          go install github.com/justtrackio/structmd@latest
          structmd $(find . | grep *.md)

      - name: Check for changes (fail if any)
        run: |
          git diff --quiet